apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf
  labels:
    app: iperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf
      release: iperf
  template:
    metadata:
      labels:
        app: iperf
        release: iperf
      name: iperf
    spec:
      containers:
      - name: iperf-tcp
        image: harbor.tools.pez.aws.grogscave.net/dockerhub/networkstatic/iperf3
        imagePullPolicy: IfNotPresent
        args:
        - -s
        ports:
        - containerPort: 5201
          name: server-tcp
          protocol: TCP
      terminationGracePeriodSeconds: 0