#@data/values
---
ingress:
  domain: <INGRESS-DOMAIN>
  base64_cert:
  base64_key:
concourse:
  username: test
  password: <PASSWORD>
harbor:
  username: admin
  password: <PASSWORD>
  diskSize: 50Gi
psp:
  cluster_role:
git:
  account: tanzu-end-to-end
  branch: main