#@ load("@ytt:data", "data")

global:
  imageRegistry: harbor.demo.tanzu.space/dockerhub
ingress:
  enabled: true
  hostname: #@ "kubeapps.{}".format(data.values.ingress.domain)
  tls: true
postgresql:
  replication:
    enabled: false
