#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: telegraf
  annotations:
    kapp.k14s.io/versioned: ""
data:
  VCENTER_HOST: #@ base64.encode(data.values.vcenter.host)
  VCENTER_USERNAME: #@ base64.encode(data.values.vcenter.username)
  VCENTER_PASSWORD: #@ base64.encode(data.values.vcenter.password)