image:
  registry: $MYSQL_REGISTRY
metrics:
  image:
    registry: $MYSQL_REGISTRY
db:
  name: petclinic
  password: petclinic
  user: petclinic
replication:
  enabled: false
root:
  password: petclinic