#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-secrets
  namespace: harbor-project-controller
  annotations:
    kapp.k14s.io/versioned: ""
data:
  harbor_host: #@ base64.encode(data.values.harbor.host)
  harbor_username: #@ base64.encode(data.values.harbor.username)
  harbor_password: #@ base64.encode(data.values.harbor.password)
