apiVersion: v1
kind: Secret
metadata:
  name: controller-secrets
  namespace: harbor-project-controller
  annotations:
    kapp.k14s.io/versioned: ""
data:
  harbor_username: YWRtaW4K
  harbor_password: SGFyYm9yMTIzNDUK
