#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  labels:
    app: webdb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      name: webdb
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb
          image: #@ "harbor.{}/{}/spring-webdb".format(data.values.ingress.domain,data.values.session)
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: webdb-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: webdb
