#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: webdb
spec:
  virtualhost:
    fqdn: default.example.com
    tls:
      secretName: #@ "{}/{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)
  routes:
    - services:
        - name: webdb
          port: 80
