#@ load("@ytt:data", "data")
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httpproxy.yaml
  - mysql.yaml
configMapGenerator:
  - name: webdb-config
    literals:
      - spring.datasource.url="jdbc:mysql://sensordb-mysql/sensors"
      - spring.datasource.username=sensors
      - spring.datasource.password=sensors
      - #@ "spring.application.name=webdb-{}".format(data.values.session)
      - management.metrics.export.wavefront.api-token=48b7b6a9-74ef-41f5-8002-f18dec9f82e2
      - management.metrics.export.wavefront.uri=https://vmware.wavefront.com
      - wavefront.application.name=webdb-e2e-workshop-w02-s001
      - wavefront.application.service=webdb
