---
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  labels:
    app: openldap
  namespace: ldap
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "YllpclVqQU5vMTVvRUpobDlWbEhzdTlpSDliZDBGUU0="
  LDAP_CONFIG_PASSWORD: "bUxnR1dWMUtjSFVCN3NLdG5nbzA0NVVhRjNidFdySFI="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-env
  labels:
    app: openldap
  namespace: ldap
data:
  LDAP_BACKEND: hdb
  LDAP_DOMAIN: e2e.vmware.com
  LDAP_ORGANISATION: Tanzu End to End Org
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
  LDAP_READONLY_USER: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldif-file
  namespace: ldap
data:
  data.ldif: |
    # Already included in default config of Docker image osixia/openldap:1.4.0.
    #
    # dn: dc=example,dc=org
    # objectClass: dcObject
    # objectClass: organization
    # o: Example Company
    # dc: example

    dn: ou=People,dc=e2e,dc=vmware,dc=com
    objectClass: organizationalUnit
    ou: People

    dn: cn=cdelashmutt,ou=People,dc=e2e,dc=vmware,dc=com
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: cdelashmutt
    displayName: Chris DeLashmutt
    givenName: Chris
    mail: cdelashmutt@vmware.com
    sn: DeLashmutt
    uid: cdelashmutt
    userPassword:: e1NTSEF9Q2loaFkyZ0lQR1k2OERXRDNkZkwzbE9EYk51ZXhBcUtWTGJFVjJYL
     29QSkxyU0NWZ0k3VUdRPT0=

    dn: cn=raoan,ou=People,dc=e2e,dc=vmware,dc=com
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: raoan
    displayName: Anand Rao
    givenName: Anand
    mail: raoan@vmware.com
    sn: Rao
    uid: raoan
    userPassword:: e1NTSEF9YmJLRmh1bXNsMy8vQlQzUWtjbTVNaFR6TENJTlRzTUJYcytQeXVsY
     TdMS2FmR1Y1MXRNcjhnPT0=

    # Group definitions.
    dn: ou=Groups,dc=e2e,dc=vmware,dc=com
    objectClass: organizationalUnit
    objectClass: top
    ou: Groups

    dn: cn=SEs,ou=Groups,dc=e2e,dc=vmware,dc=com
    objectClass: groupOfNames
    objectClass: top
    cn: SEs
    member: cn=cdelashmutt,ou=People,dc=e2e,dc=vmware,dc=com
    member: cn=raoan,ou=People,dc=e2e,dc=vmware,dc=com

#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: openldap
#  labels:
#    app: openldap
#  namespace: ldap
#spec:
#  accessModes:
#    - "ReadWriteOnce"
#  resources:
#    requests:
#      storage: "8Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
  namespace: ldap
spec:
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: ldap-port
    - name: ssl-ldap-port
      protocol: TCP
      port: 636
      targetPort: ssl-ldap-port
  selector:
    app: openldap
    release: openldap
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
      release: openldap
  template:
    metadata:
      labels:
        app: openldap
        release: openldap
    spec:
      containers:
        - name: openldap
          image: "osixia/openldap:1.2.4"
          imagePullPolicy: IfNotPresent
          args:
            - --copy-service
            - -l
            - info
          ports:
            - name: ldap-port
              containerPort: 389
            - name: ssl-ldap-port
              containerPort: 636
          envFrom:
            - configMapRef:
                name: openldap-env
            - secretRef:
                name: openldap
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: data
            - name: data
              mountPath: /etc/ldap/slapd.d
              subPath: config-data
            - name: ldif
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          env:
          livenessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {}
      volumes:
        - name: certs
          emptyDir:
            medium: Memory
        - name: data
          emptyDir: 
            medium: Memory
#          persistentVolumeClaim:
#            claimName: openldap
        - name: ldif
          configMap:
            name: ldif-file
            items:
            - key: data.ldif
              path: data.ldif
