---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-cluster-admin-sa
  namespace: concourse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapp-admin-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapp-admin-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kapp-cluster-admin-sa
  namespace: concourse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapp-cluster-admin-cluster-role