#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-secrets
  namespace: argocd-project-controller
data:
  argocd_host: #@ base64.encode("argocd-cli.{}".format(data.values.ingress.domain))
  argocd_username: #@ base64.encode("admin")
  argocd_password: #@ base64.encode(data.values.argocd.adminPassword)
