apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argocdprojects.e2e.tanzu.vmware.com
  namespace: argocd-project-controller
spec:
  group: e2e.tanzu.vmware.com
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              name: 
                type: string
          status:
            type: object
            nullable: true
            properties:
              projectid:
                type: string
                nullable: true
              error:
                type: string
                nullable: true
  names:
    kind: ArgoCDProject
    plural: argocdprojects
    singular: argocdproject
  scope: Namespaced
  subresources:
    status: {}