#@ load("@ytt:data", "data")

service:
  http:
    clusterIP:
ingress:
  enabled: true
  hosts: #@ ["gitea.{}".format(data.values.ingress.domain)]
  tls:
    - secretName: #@ "{}/{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)
      hosts: #@ ["gitea.{}".format(data.values.ingress.domain)]
gitea:
  admin:
    password: #@ data.values.gitea.adminPassword
  config:
    repository:
      ENABLE_PUSH_CREATE_USER: true
      DEFAULT_BRANCH: main