#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-secrets
  namespace: concourse-team-controller
data:
  concourse_url: #@ base64.encode("https://concourse.{}".format(data.values.ingress.domain))
  concourse_username: #@ base64.encode(data.values.concourse.username)
  concourse_password: #@ base64.encode(data.values.concourse.password)
