apiVersion: v1
kind: Secret
metadata:
  name: controller-secrets
  namespace: concourse-team-controller
  annotations:
    kapp.k14s.io/versioned: ""
data:
  concourse_username: dGVzdAo=
  concourse_password: dGVzdAo=
